### ISSUE TITLE
Is Old 3DS ver 9.0.0-20U not supported?

### ISSUE THREAD

**Issue by MrMonotone** [yellows8/3ds_webkithax#2]
You mention something about the first version of the browser not being supported by this exploit? Does that mean ver 9.0.0 ? If not I am having problems launching homebrew  launcher using "sliderhax." The behavior that is being exhibited is the slider loads. I am able to click the slider. Sometimes the exploit will crash to homemenu. However I know that this hack is somewhat unreliable. On the other hand if the exploit executes the bottom screen flashes yellow then grey. The top screen stays the same. After this the program seems to hang and no button presses can be used. I have to hard reset the 3ds by holding down the power button. Is there a debug that I could provide you to better understand if it is a issue with this exploit or the homebew launcher?

**Comment by yellows8** [comment]
"first version of the browser" http://3dbrew.org/wiki/Internet_Browser#User-Agent_and_Browser_Versions_2

In theory it was "supposed" to work on all system-versions(due to hblauncher-payload) starting with v9.0. But the only Old3DS system-versions I tested with it(hblauncher loader) are v9.9 and v10.X.

EDIT:
Did you ever tinker with anything in your NAND?

EDIT2:
"Is there a debug that I could provide you to better understand if it is a issue with this exploit or the homebew launcher?" No, it's probably an issue with my hblauncher-payload loader.

**Comment by MrMonotone** [comment]
I just upgraded my NAND to 9.2.0-20U. I have tested it on there and still no luck. I had the MSET exploit before on 9.0.0 U. However it was removed in the upgrade. I did not reinstall it. Could you send me a payload that has some debug to help improve compatibility? On the otherhand you just might not care about O3DS on older firmwares which is fine. However I find the problem interesting. I will check my browser version later and post that.

**Comment by yellows8** [comment]
I'll work on debugging it myself on v9.2 later.

**Comment by yellows8** [comment]
My menustub code is running, but it's failing to find the target data. Working on debugging/fixing...

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_browserhax_common/commit/56555e261bd49eb7a5984f2b8a75bd5661486f86 This issue will be closed once @MrMonotone verifies that it works fine on their system(it works here now).

**Comment by MrMonotone** [comment]
confirmed working OLD 3DS v9.2-20. thanks for your work :+1:
